[programs.devnet]
myepicproject = "AJFkCag6f8fzDN8RwogJpYppBCYNRH2WqDaUbWKyLgeq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/josefigueroa/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 